### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [infinity0/debcopy#1]
What would be the license for this code?
Thanks!

**Comment by infinity0** [comment]
You can consider it licensed under AGPL 3. But it's just play code and I wrote it whilst discussing changes I wanted make to the actual real Debian copyright format, and those changes weren't adopted, so this code wouldn't be useful for anything. There is other code already in Debian that actually parses the real standard. I don't know where exactly but you can go find it yourself.

**Comment by pombredanne** [comment]
Thanks!
